### ISSUE TITLE
What a nice website

### ISSUE THREAD

**Issue by jackherizsmith** [fac20/Week-1-PartyWave-CEFG#24]
I love the colours and layout and spacing of your site, very relaxed and positive vibes - exactly the kind of agency I want to work with.

And Pacifico is lovely!

One thing you should fix before the presentation though is the form which can be sent when empty. From the acceptance criteria:

> A user cannot submit a form without filling out all of the mandatory fields (name, company name, email address)

Those specific fields aren't important, but being able to prevent an empty form from being sent is.

**Comment by LiCern** [comment]
The form was fixed to prevent it from being sent empty to satisfy the acceptance criteria. 

Thank you for the compliments! 

p.s. Pacifico is definitely a favourite font! 😊
