### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by jessica440** [fac20/Week-1-PartyWave-CEFG#32]
Lighthouse report is 69%. Consider
- [x] Astronaut image needs to have an alt tag (for ChromeVox)
- [x] Form elements - text area needs an id, name label needs an id
- [x] Need to add tab index (main content not accessible by ChromeVox)

**Comment by JoshDAO** [comment]
Regarding the tab index, you might be ok. We have very much misunderstood its purpose :laughing:
