### ISSUE TITLE
<br> tag alternative

### ISSUE THREAD

**Issue by Netceer** [fac20/Week-1-PartyWave-CEFG#34]
If the goal of the `<br>` tags is to split paragraphs then a potential alternative method is to use mulitple `<p>` tags instead and control spaceing with margin and padding rules.

I think this might be better from an accessbility standpoint, please see paragraph below I got from MDN about `<br>`:

_Accessibility concerns 
Creating separate paragraphs of text using `<br>` is not only bad practice, it is problematic for people who navigate with the aid of screen reading technology. Screen readers may announce the presence of the element, but not any content contained within `<br>`s. This can be a confusing and frustrating experience for the person using the screen reader._

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br#:~:text=Creating%20separate%20paragraphs%20of%20text,contained%20within%20s.

**Comment by khadija-nur** [comment]
Thanks! this is very helpful
